# Generated by Django 2.2.10 on 2020-06-23 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('R', 'Regular'), ('S', 'Sicilian')], max_length=10)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='SubExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DinnerPlatterOrder',
            fields=[
                ('dinnerplatter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.DinnerPlatter')),
                ('quantity', models.IntegerField(default=1)),
            ],
            bases=('orders.dinnerplatter',),
        ),
        migrations.CreateModel(
            name='PastaOrder',
            fields=[
                ('pasta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Pasta')),
                ('quantity', models.IntegerField(default=1)),
            ],
            bases=('orders.pasta',),
        ),
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('pizza_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Pizza')),
                ('extras', models.CharField(choices=[('CH', 'Cheese'), ('1', '1 Topping'), ('2', '2 Toppings'), ('3', '3 Toppings'), ('SP', 'Special')], default='CH', max_length=15)),
                ('quantity', models.IntegerField(default=1)),
            ],
            bases=('orders.pizza',),
        ),
        migrations.CreateModel(
            name='SaladOrder',
            fields=[
                ('salad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Salad')),
                ('quantity', models.IntegerField(default=1)),
            ],
            bases=('orders.salad',),
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('sub_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Sub')),
                ('quantity', models.IntegerField(default=1)),
            ],
            bases=('orders.sub',),
        ),
        migrations.AddField(
            model_name='sub',
            name='extras',
            field=models.ManyToManyField(blank=True, to='orders.SubExtra'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Price in USD', max_digits=6)),
                ('dinnerPlatters', models.ManyToManyField(blank=True, to='orders.DinnerPlatter')),
                ('pastas', models.ManyToManyField(blank=True, to='orders.Pasta')),
                ('pizzas', models.ManyToManyField(blank=True, to='orders.Pizza')),
                ('salads', models.ManyToManyField(blank=True, to='orders.Salad')),
                ('subExtras', models.ManyToManyField(blank=True, to='orders.SubExtra')),
                ('subs', models.ManyToManyField(blank=True, to='orders.Sub')),
                ('toppings', models.ManyToManyField(blank=True, to='orders.Topping')),
            ],
        ),
    ]
