# Generated by Django 3.0.7 on 2020-06-06 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaprice',
            name='size',
            field=models.ForeignKey(default='S', on_delete=django.db.models.deletion.PROTECT, to='orders.Size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizzaprice',
            name='type',
            field=models.ForeignKey(default='REG', on_delete=django.db.models.deletion.PROTECT, to='orders.PizzaType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizzaprice',
            name='toppings',
            field=models.IntegerField(default=0),
        ),
    ]
