# Generated by Django 3.0.7 on 2020-06-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pasta_pizza_pizzatype_platter_salad_sub_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='numToppings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
