# Generated by Django 3.0.7 on 2020-06-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200606_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaprice',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
