# Generated by Django 3.0.7 on 2020-06-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_pizzaprice_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzaprice',
            name='special',
        ),
    ]
