# Generated by Django 2.2.10 on 2020-06-22 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_pizza_numtoppings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('pizza_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Pizza')),
                ('extras', models.CharField(choices=[('CH', 'Cheese'), ('1', '1 Topping'), ('2', '2 Toppings'), ('3', '3 Toppings'), ('SP', 'Special')], default='CH', max_length=15)),
                ('quantity', models.IntegerField(default=1)),
            ],
            bases=('orders.pizza',),
        ),
        migrations.CreateModel(
            name='SubExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Platter',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='largePrice',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='numToppings',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='smallPrice',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='largePrice',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='smallPrice',
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(default=0, help_text='Price in USD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='style',
            field=models.CharField(choices=[('R', 'Regular'), ('S', 'Sicilian')], default='R', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='sub',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in USD', max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pasta',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=6),
        ),
        migrations.AlterField(
            model_name='salad',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='salad',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=6),
        ),
        migrations.AlterField(
            model_name='sub',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='PizzaType',
        ),
        migrations.AddField(
            model_name='sub',
            name='extras',
            field=models.ManyToManyField(blank=True, to='orders.SubExtra'),
        ),
    ]
